version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "13.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: "jerome.sonnet@be-cloud.be"
      PGDATABASE: &dbname horizon
      PGUSER: &dbuser "odoo"
      DB_FILTER: ".*"
      PROXY_MODE: "false"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z

  db:
    image: ghcr.io/tecnativa/postgres-autoconf:13-alpine
    shm_size: 512mb
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    image: mailhog/mailhog

  backup:
    image: tecnativa/duplicity:postgres
    hostname: backup
    init: true
    environment:
      DST: "gs://bucket/be-cloud/odoo/backup"
      PGDATABASE: *dbname
      PGUSER: *dbuser
      TZ: "UTC"
    volumes:
      - backup_cache:/root:z
      - filestore:/mnt/backup/src/odoo:z
